### PR TITLE
Fix original authors name

### PR DESCRIPTION
**Pull request by fwolfst**

### CODE REVIEW

**Comment by willfish** [comment]
@fwolfst I accidentally pushed to master on our fork and rewrote the commit log. You'll want to take the latest commit as its the same code (just with a different sha)

**Comment by willfish** [comment]
Sorry if this negatively effected your build process

**Comment by fwolfst** [comment]
Wow, how did you derive that i came back to this fork and checked the commit history because of failing build processes? :D 🕵️ . Thanks.

**Comment by willfish** [comment]
No problem at all :). I just figured you're maintaining an application that depends on this functionality as opened this PR. Hope I didn't cause you too much pain

**Pull request merged**
